"""Declarative base and reusable mixins for SQLAlchemy models.

No domain model lives here yet (see docs/architecture.md §3, phase 2). This
module only lays the foundation every future model builds on: a shared
metadata object for Alembic autogenerate to inspect, plus the id and
timestamp columns that architecture.md §4.2/§4.3 repeats on every table.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Shared declarative base. `Base.metadata` is what Alembic autogenerate diffs against."""


class UUIDPrimaryKeyMixin:
    """`id: uuid` primary key, generated by Postgres itself.

    `gen_random_uuid()` is built into Postgres 13+ (no pgcrypto extension
    needed), so the id is assigned by the database on INSERT rather than
    round-tripped from Python.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """`created_at` / `updated_at`, both `timestamptz`, set by Postgres.

    `updated_at` is refreshed via `onupdate` on the ORM side; a future
    migration adding a DB-level trigger would only strengthen this, not
    replace it, since raw SQL updates bypass ORM-side `onupdate`.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
